### ISSUE TITLE
Change version after release

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-server#100]
In the current release process, after a new release is made, the version number is unchanged.
As a result, all successive dev versions will display the same version number as the previously made release. Which may confuse users believing they are using the latest release while they are using an unreleased dev version.

Suggested change :
Update the release process to change the version number to something like 1.X.X-dev after the release is made.

This change is to be made on each project: server, client, player.

**Comment by Neraste** [comment]
I think this is a good idea. Keeping the same version number for releases and development branch was misleading. But I am pretty sure this would not be a problem if users stick to releases.

According to the [PEP440](https://www.python.org/dev/peps/pep-0440/#post-release-separators), about versioning, we should use a version number like `1.X.X-post`, as we want to indicate a post-release version. `-dev` would indicate a pre-release version.

If the server, front or player runs on a post-release version, maybe we should display a message somewhere warning that the user runs a non-release version at them own risks.

As a side note, I think it would be nice to add on the front and on the player a verification of the server version. If the sever version does not match the major.minor version, an error message is displayed.

**Comment by Neraste** [comment]
The concept of pre-release is found nowhere but in the PEP440. Especially, it is not supported by [SemVer](https://semver.org/), and article 10 states that version metadata should be ignored to determine version precedence.

So when releasing `1.X.X`, we should instead change the version number on dev branch to `1.Y.X-dev` (*i.e.* the dev version of the next release).

**Comment by Neraste** [comment]
Fixed by #102.
