### ISSUE TITLE
Improve feeder when matching files with similar names

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-server#25]
When a file is renamed and a file with similar name is added, the first of the new file is match with the previous database entry.

Improvement : use the filename with best matching

**Comment by Neraste** [comment]
This involves looping on every file first to obtain a matrix of matching ratio, then re looping on every file to associate with the most similar one. This is very different from the current feeding design, where only one loop over files is done.

**Comment by Nadeflore** [comment]
Idea: create a matrix deleted-created of ratios, then find recursively the largest ones and remove the line and column.

**Comment by Neraste** [comment]
Now managed by the feeder.
