### ISSUE TITLE
Disable tags + tags configuration 

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-server#36]
Allow tags to be disabled. 
When disabled, songs with these tags do not appear in search, and cannot be added to playlist.
Tags can be configured (color and disabled state) by library manager

**Comment by Neraste** [comment]
Tasks to do:

* Add enabled/disabled Boolean in Tag model;
* Route to display/edit tags;
* Exclude musics from listing/search if one of their tag is disabled;
* Forbid to add musics to playlist if one of their tag is disabled.

**Comment by Neraste** [comment]
Done by 87a9e49.
