### ISSUE TITLE
Additional information for Artists

### ISSUE THREAD

**Issue by Benstales** [DakaraProject/dakara-server#72]
The current state of the Dakara allows to feed information to the database related to artists only with the feed command, that is to say, during song creation. It should be more practical for some users to associate the artist to its songs once these songs are created.

An approach fitting for this is to make a createartists command looking like createworks which takes a metadata file as input and some optional arguments (parser, debug mode,...). For each artist we would associate a set of songs, this would create artists and add to the songs the artist performing it.

**Comment by Benstales** [comment]
I like more your idea. Since this command creates artists during the song creation, it should also create works associated to this song if they don't exist (which is already the case in the "scan mode" btw).

**Comment by Neraste** [comment]
This issue concerns an old version of Dakara.
