### ISSUE TITLE
No time update when player is restarted

### ISSUE THREAD

**Issue by Nadeflore** [DakaraProject/dakara-server#97]
Steps to reproduce:
- Start playing a song
- Pause the song
- Exit the player
- Restart the player

Current song time is not updated anymore and stays at 0:00 because the in memory player is still paused = true

**Comment by Neraste** [comment]
I cannot reproduce this bug (neither on dev environment, nor in prod). I don't mean the PR I made is meaningless now, but I wonder how we could get this bug.

**Comment by Neraste** [comment]
What I have however is when the player is stopped, the timing continues to progress on the client. My PR should fix that.

**Comment by Nadeflore** [comment]
I was able to reproduce,
The player actually needs to be pause before exiting for the bug to occur.

I edited the issue to reflect this.
